### ISSUE TITLE
Cut a release?

### ISSUE THREAD

**Issue by chenrui333** [stealthrocket/timecraft#223]
Now we are with go1.21, maybe cut a release for downstream packaging consumption? Let me know what you think. Thanks!

**Comment by Pryz** [comment]
Hi @chenrui333, yes we will cut a new release pretty soon!

**Comment by chenrui333** [comment]
that is exciting!

**Comment by Pryz** [comment]
We tagged v0.1.0. I would love to hear more about your use case :)
